import { useState, useEffect } from 'react';
import { Map, Camera, Music } from 'lucide-react';

interface OnboardingScreenProps {
  onComplete: () => void;
}

const SLIDES = [
  {
    title: "Be an Explorer",
    description: "Welcome to Echoes of the Ancestors. You are about to embark on an expedition across the Visayas to uncover lost musical traditions.",
    // Pale Dusty Pink for a soft, inviting opening
    icon: <Map size={140} className="text-[#f0dde0] drop-shadow-[0_0_35px_rgba(240,221,224,0.4)]" />,
    glowColor: "bg-[#2a2d43]/40", // Dark Slate / Navy undertone
    blobColor: "bg-[#2a2d43]", 
  },
  {
    title: "Discover Instruments",
    description: "Use your device's camera to scan real traditional Philippine instruments in museums or cultural centers to add them to your collection.",
    // Crimson tied directly to the scanning/discovery action
    icon: <Camera size={140} className="text-[#da2d46] drop-shadow-[0_0_35px_rgba(218,45,70,0.6)]" />,
    glowColor: "bg-[#da2d46]/20",
    blobColor: "bg-[#da2d46]",
  },
  {
    title: "Play & Learn",
    description: "Play rhythmic minigames to master the instruments, earn XP, and unlock dynamic stories generated by the Ancestors.",
    // Gold applied to XP/Progression as per the design notes
    icon: <Music size={140} className="text-[#c49a4c] drop-shadow-[0_0_35px_rgba(196,154,76,0.6)]" />,
    glowColor: "bg-[#c49a4c]/20",
    blobColor: "bg-[#c49a4c]",
  }
];

export function OnboardingScreen({ onComplete }: OnboardingScreenProps) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [fireflies, setFireflies] = useState<{ id: number; left: string; top: string; delay: string; duration: string }[]>([]);

  // Generate random fireflies only on client side to avoid hydration mismatch
  useEffect(() => {
    const particles = Array.from({ length: 25 }).map((_, i) => ({
      id: i,
      left: `${Math.random() * 100}%`,
      top: `${Math.random() * 100}%`,
      delay: `${Math.random() * 5}s`,
      duration: `${Math.random() * 10 + 15}s`, // 15-25s floating duration
    }));
    setFireflies(particles);
  }, []);

  const handleNext = () => {
    if (currentSlide < SLIDES.length - 1) {
      setCurrentSlide(prev => prev + 1);
    } else {
      onComplete();
    }
  };

  return (
    // Swapped to Near Black (#0f0c0c) base
    <div className={`relative min-h-screen flex flex-col pb-safe font-sans text-white overflow-hidden transition-colors duration-1000 bg-[#0f0c0c]`}>
      
      {/* --- INTERACTIVE BACKGROUND ELEMENTS --- */}
      
      {/* 1. Ambient Background Glow matching current slide */}
      <div className={`absolute inset-0 transition-colors duration-1000 ${SLIDES[currentSlide].glowColor} mix-blend-overlay opacity-50`} />

      {/* 2. Animated Mesh Gradient Blobs */}
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none z-0">
        <div className={`absolute -top-[10%] -left-[10%] w-[500px] h-[500px] rounded-full mix-blend-screen filter blur-[120px] opacity-20 animate-blob transition-colors duration-1000 ${SLIDES[currentSlide].blobColor}`} />
        <div className={`absolute top-[20%] -right-[10%] w-[400px] h-[400px] rounded-full mix-blend-screen filter blur-[100px] opacity-15 animate-blob animation-delay-2000 transition-colors duration-1000 ${SLIDES[currentSlide].blobColor}`} />
        <div className={`absolute -bottom-[10%] left-[20%] w-[600px] h-[600px] rounded-full mix-blend-screen filter blur-[120px] opacity-15 animate-blob animation-delay-4000 transition-colors duration-1000 bg-[#da2d46]`} />
      </div>

      {/* 3. Ancestral Fireflies (Particles) - Now using Gold (#c49a4c) */}
      <div className="absolute inset-0 z-0 pointer-events-none">
        {fireflies.map((ff) => (
          <div
            key={ff.id}
            className="absolute rounded-full bg-[#c49a4c] shadow-[0_0_8px_2px_rgba(196,154,76,0.5)] animate-firefly"
            style={{
              width: '3px',
              height: '3px',
              left: ff.left,
              top: ff.top,
              animationDelay: ff.delay,
              animationDuration: ff.duration,
            }}
          />
        ))}
      </div>

      {/* --- FOREGROUND CONTENT --- */}
      <div className="relative z-10 flex-1 flex flex-col justify-center items-center px-10 text-center">
        
        {/* Floating Illustration */}
        <div className="mb-16 animate-float transition-transform duration-500 ease-out">
          {SLIDES[currentSlide].icon}
        </div>

        {/* Clean Typography */}
        <div className="space-y-5 h-32"> 
          <h2 className="text-3xl font-bold tracking-wide animate-fade-in text-[#f0dde0]">
            {SLIDES[currentSlide].title}
          </h2>
          
          {/* Lore text using Warm Parchment (#f4eadd) */}
          <p className="text-[16px] text-[#f4eadd] leading-relaxed max-w-sm animate-fade-in animation-delay-300 opacity-90">
            {SLIDES[currentSlide].description}
          </p>
        </div>
      </div>

      {/* Minimalist Bottom Navigation */}
      <div className="relative z-10 flex justify-between items-center px-8 pb-12 pt-6">
        
        {/* Skip Button - Slate Gray to Pale Dusty Pink */}
        <button 
          onClick={onComplete}
          className={`text-xs font-bold tracking-widest transition-opacity duration-300 uppercase ${
            currentSlide === SLIDES.length - 1 
              ? 'opacity-0 pointer-events-none' 
              : 'opacity-100 text-[#888ea1] hover:text-[#f0dde0]'
          }`}
        >
          Skip
        </button>

        {/* Minimal Pagination Dots */}
        <div className="flex justify-center gap-3">
          {SLIDES.map((_, idx) => (
            <div 
              key={idx} 
              className={`rounded-full transition-all duration-500 ${
                currentSlide === idx 
                  ? 'w-6 h-1.5 bg-[#da2d46] shadow-[0_0_10px_rgba(218,45,70,0.8)]' 
                  : 'w-1.5 h-1.5 bg-[#888ea1] opacity-40 hover:bg-[#e0e5ed]'
              }`}
            />
          ))}
        </div>

        {/* Next / Get Started Button - Crimson */}
        <button 
          onClick={handleNext}
          className="text-xs font-bold tracking-widest text-[#da2d46] hover:text-[#f0dde0] hover:drop-shadow-[0_0_8px_rgba(218,45,70,0.8)] transition-all duration-300 uppercase"
        >
          {currentSlide === SLIDES.length - 1 ? 'Get Started' : 'Next'}
        </button>

      </div>
      
      {/* Custom Keyframes remain unchanged */}
      <style>{`
        @keyframes float {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-15px); }
        }
        @keyframes blob {
          0% { transform: translate(0px, 0px) scale(1); }
          33% { transform: translate(30px, -50px) scale(1.1); }
          66% { transform: translate(-20px, 20px) scale(0.9); }
          100% { transform: translate(0px, 0px) scale(1); }
        }
        @keyframes firefly {
          0% { transform: translateY(0) translateX(0) scale(1); opacity: 0; }
          10% { opacity: 1; }
          50% { transform: translateY(-100px) translateX(20px) scale(1.5); opacity: 0.8; }
          90% { opacity: 0; }
          100% { transform: translateY(-200px) translateX(-20px) scale(1); opacity: 0; }
        }
        @keyframes fade-in {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-float { animation: float 6s ease-in-out infinite; }
        .animate-blob { animation: blob 10s infinite alternate; }
        .animate-firefly { animation: firefly linear infinite; }
        .animate-fade-in { animation: fade-in 0.6s ease-out forwards; }
        .animation-delay-300 { animation-delay: 300ms; }
        .animation-delay-2000 { animation-delay: 2s; }
        .animation-delay-4000 { animation-delay: 4s; }
      `}</style>
    </div>
  );
}