import { useState } from 'react';
import { Map, Camera, Music } from 'lucide-react';

interface OnboardingScreenProps {
  onComplete: () => void;
}

const SLIDES = [
  {
    title: "Be an Explorer",
    description: "Welcome to Echoes of the Ancestors. You are about to embark on an expedition across the Visayas to uncover lost musical traditions.",
    icon: <Map size={140} className="text-blue-300 drop-shadow-2xl" />,
  },
  {
    title: "Discover Instruments",
    description: "Use your device's camera to scan real traditional Philippine instruments in museums or cultural centers to add them to your collection.",
    icon: <Camera size={140} className="text-pink-300 drop-shadow-2xl" />,
  },
  {
    title: "Play & Learn",
    description: "Play rhythmic minigames to master the instruments, earn XP, and unlock dynamic stories generated by the Ancestors.",
    icon: <Music size={140} className="text-emerald-300 drop-shadow-2xl" />,
  }
];

export function OnboardingScreen({ onComplete }: OnboardingScreenProps) {
  const [currentSlide, setCurrentSlide] = useState(0);

  const handleNext = () => {
    if (currentSlide < SLIDES.length - 1) {
      setCurrentSlide(prev => prev + 1);
    } else {
      onComplete();
    }
  };

  return (
    // Deep slate/navy background matching the reference image vibe
    <div className="relative min-h-screen bg-[#2a2d43] flex flex-col pb-safe font-sans text-white overflow-hidden">
      
      {/* Main Content Area */}
      <div className="flex-1 flex flex-col justify-center items-center px-10 text-center">
        
        {/* Floating Illustration */}
        <div className="mb-16 animate-float">
          {SLIDES[currentSlide].icon}
        </div>

        {/* Clean Typography */}
        <h2 className="text-2xl font-bold mb-5 tracking-wide">
          {SLIDES[currentSlide].title}
        </h2>
        
        <p className="text-[15px] text-gray-400 leading-relaxed max-w-sm">
          {SLIDES[currentSlide].description}
        </p>

      </div>

      {/* Minimalist Bottom Navigation */}
      <div className="flex justify-between items-center px-8 pb-12 pt-6">
        
        {/* Skip Button */}
        <button 
          onClick={onComplete}
          className={`text-xs font-bold tracking-widest transition-opacity duration-300 uppercase ${
            currentSlide === SLIDES.length - 1 
              ? 'opacity-0 pointer-events-none' 
              : 'opacity-100 text-gray-400 hover:text-white'
          }`}
        >
          Skip
        </button>

        {/* Minimal Pagination Dots */}
        <div className="flex justify-center gap-2">
          {SLIDES.map((_, idx) => (
            <div 
              key={idx} 
              className={`rounded-full transition-all duration-300 ${
                currentSlide === idx 
                  ? 'w-2 h-2 bg-[#da2d46] scale-110' 
                  : 'w-1.5 h-1.5 bg-[#f0dde0] opacity-50'
              }`}
            />
          ))}
        </div>

        {/* Next / Get Started Button */}
        <button 
          onClick={handleNext}
          className="text-xs font-bold tracking-widest text-[#da2d46] hover:text-[#f0dde0] transition-colors uppercase"
        >
          {currentSlide === SLIDES.length - 1 ? 'Get Started' : 'Next'}
        </button>

      </div>
      
      {/* Simple float animation */}
      <style>{`
        @keyframes float {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-12px); }
        }
        .animate-float { animation: float 5s ease-in-out infinite; }
      `}</style>
    </div>
  );
}