import { useState } from 'react';
import { Map, Camera, Music, ChevronRight, ChevronLeft } from 'lucide-react';

interface OnboardingScreenProps {
  onComplete: () => void;
}

const SLIDES = [
  {
    title: "THE JOURNEY BEGINS",
    description: "Welcome to Echoes of the Ancestors. You are about to embark on an expedition across the Visayas to uncover lost musical traditions.",
    icon: <Map size={64} className="text-crimson" />,
    color: "from-crimson/20",
  },
  {
    title: "DISCOVER",
    description: "Use your device's camera to scan real traditional Philippine instruments in museums or cultural centers to add them to your collection.",
    icon: <Camera size={64} className="text-pale-pink" />,
    color: "from-pale-pink/20",
  },
  {
    title: "PLAY & LEARN",
    description: "Play rhythmic minigames to master the instruments, earn XP, and unlock dynamic stories generated by the Ancestors.",
    icon: <Music size={64} className="text-light-gray" />,
    color: "from-light-gray/20",
  }
];

export function OnboardingScreen({ onComplete }: OnboardingScreenProps) {
  const [currentSlide, setCurrentSlide] = useState(0);

  const handleNext = () => {
    if (currentSlide < SLIDES.length - 1) {
      setCurrentSlide(prev => prev + 1);
    } else {
      onComplete();
    }
  };

  const handlePrev = () => {
    if (currentSlide > 0) {
      setCurrentSlide(prev => prev - 1);
    }
  };

  const slide = SLIDES[currentSlide];

  return (
    <div className="relative min-h-screen bg-obsidian flex flex-col pb-safe overflow-hidden">
      
      {/* Background Gradient */}
      <div className={`absolute inset-0 bg-gradient-to-br ${slide.color} to-transparent opacity-30 transition-colors duration-1000`} />
      
      <div className="flex-1 flex flex-col justify-center items-center p-8 relative z-10 text-center">
        
        {/* Icon container with bounce animation */}
        <div className="w-40 h-40 rounded-full bg-dark-slate/50 border border-light-gray/10 flex items-center justify-center mb-10 shadow-2xl backdrop-blur-sm relative animate-float">
          <div className="absolute inset-0 bg-gradient-to-t from-dark-slate to-transparent rounded-full opacity-50" />
          <div className="relative z-10">
            {slide.icon}
          </div>
        </div>

        <h2 className="font-orbitron font-black text-3xl text-light-gray mb-4 tracking-wider">
          {slide.title}
        </h2>
        
        <p className="font-space-mono text-sm text-light-gray/70 leading-relaxed max-w-sm">
          {slide.description}
        </p>

      </div>

      {/* Controls */}
      <div className="p-8 relative z-10">
        
        {/* Pagination Dots */}
        <div className="flex justify-center gap-3 mb-8">
          {SLIDES.map((_, idx) => (
            <div 
              key={idx} 
              className={`h-1.5 rounded-full transition-all duration-300 ${currentSlide === idx ? 'w-8 bg-crimson glow-crimson' : 'w-2 bg-light-gray/20'}`}
            />
          ))}
        </div>

        <div className="flex justify-between items-center gap-4">
          <button 
            onClick={handlePrev}
            className={`w-14 h-14 flex items-center justify-center rounded-2xl border transition-all ${currentSlide === 0 ? 'opacity-0 pointer-events-none' : 'opacity-100 border-light-gray/20 text-light-gray hover:bg-dark-slate active:scale-95'}`}
          >
            <ChevronLeft size={24} />
          </button>

          <button 
            onClick={handleNext}
            className="flex-1 h-14 rounded-2xl font-orbitron text-sm font-bold tracking-widest uppercase
              bg-gradient-to-r from-crimson to-pale-pink text-obsidian
              hover:shadow-lg hover:shadow-crimson/40 active:scale-[0.98]
              transition-all duration-200 flex items-center justify-center gap-2"
          >
            {currentSlide === SLIDES.length - 1 ? 'BEGIN EXPEDITION' : 'NEXT'} 
            {currentSlide === SLIDES.length - 1 ? null : <ChevronRight size={20} />}
          </button>
        </div>

      </div>
      
      <style>{`
        @keyframes float {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-10px); }
        }
        .animate-float { animation: float 6s ease-in-out infinite; }
      `}</style>
    </div>
  );
}
